project:
  type: book
  output-dir: docs

book:
  downloads: [pdf]
  title: " "
  subtitle: " "
  reader-mode: true
  page-footer:
    left: |
      *Przewodnik dla jednostek służb statystyki publicznej w zakresie kontroli ujawniania danych statystycznych* został przygotowany przez **Zespół ds. metod kontroli ujawniania danych statystycznych**.
  search:
    location: navbar
    type: textbox

  chapters:
    - index.qmd
    - dictionary00_2.qmd
    - intro01.qmd
    - aim02.qmd
    - law03.qmd
    - met04.qmd

    
bibliography: references.bib

format:
  html:
    theme: 
      light: flatly
      dark: darkly
      
  pdf:
    documentclass: scrreprt

css: custom.css
selfcontained: true
reference-location: margin
engine: knitr
toc: true
toc-depth: 3
fig-cap-location: top
number-sections: true