# Cel i założenia dokumentu  

::: {.justify}

Przestrzeganie zasad tajemnicy statystycznej jest jednym z fundamentów, na których opiera się funkcjonowanie statystyki publicznej. Jest to kwestia zapewnienia ochrony danych, które krajowym instytucjom statystycznym są przekazywane przez respondentów (obywatele, podmioty gospodarcze, instytucje, jednostki samorządu terytorialnego i inne). Bez zapewnienia ochrony danych trudno mówić o zaufaniu respondentów do urzędu statystycznego, a w konsekwencji do *gwarancji rzetelnego, obiektywnego i systematycznego informowania społeczeństwa, organów państwa i administracji publicznej oraz podmiotów gospodarki narodowej o sytuacji ekonomicznej, demograficznej, społecznej oraz środowiska naturalnego* (art. 3 Ustawy z dnia 29 czerwca 1995 r. o statystyce publicznej, zwanej dalej Ustawą).

Głównym celem dokumentu, z punktu widzenia instytucji, jest zebranie i zaprezentowanie w jednym opracowaniu aktualnych – obecnie rozproszonych po różnych komórkach i jednostkach statystyki publicznej (departamenty Głównego Urzędu Statystycznego, urzędy statystyczne) – wiedzy i doświadczeń, jakimi dysponuje statystyka publiczna w Polsce w odniesieniu do zagadnień związanych z tajemnicą statystyczną oraz kontrolą ujawniania danych statystycznych. To rozproszenie wiedzy jest m.in. konsekwencją specjalizacji badawczej poszczególnych komórek organizacyjnych, która spowodowała wytworzenie odrębnych podejść do zagadnień ochrony tajemnicy statystycznej przez jednostki autorskie poszczególnych badań zawartych w programie badań statystycznych statystyki publicznej, wynikających ze specyfiki tych badań i obejmowanych nimi danych. W *Przewodniku* uwzględniono doświadczenia wynikające ze współpracy międzynarodowej w zakresie m.in. zagadnień związanych z ochroną danych objętych tajemnicą statystyczną i kontrolą jakości danych statystycznych oraz będące wynikiem śledzenia rozwoju metod i technik analitycznych związanych z tą problematyką. Opracowanie oraz wdrożenie jednolitego podejścia do ochrony tajemnicy statystycznej i stosowania metod kontroli ujawniania danych statystycznych, przy uwzględnieniu różnych typów danych i form ich udostępniania, przyczyni się do podniesienia jakości funkcjonowania statystyki publicznej w Polsce, a przede wszystkim zwiększenia bezpieczeństwa danych będących w jej posiadaniu. 

*Przewodnik* stanowi zatem kompendium aktualnej wiedzy dla pracowników służb statystyki publicznej w zakresie poprawnego rozumienia i stosowania zasad ochrony tajemnicy statystycznej. W założeniu Zespołu będzie on w przyszłości aktualizowany i uzupełniany zgodnie z rozwojem wiedzy w tym zakresie. Stanowi on także element podnoszenia kompetencji oraz jakości kadr statystyki publicznej dzięki prezentacji nowoczesnych metod i narzędzi służących zapewnieniu ochrony danych statystycznych objętych tajemnicą statystyczną. 

Aspekty prawne związane z tajemnicą statystyczną są szczegółowo przedstawione w trzecim rozdziale *Przewodnika* [Podstawy prawne tajemnicy statystycznej](law03.qmd#sec-law), natomiast warto zauważyć w tym miejscu, że dwie spośród wielu metod kontroli ujawniania danych zawarte są wprost w Ustawie. Jedną z nich jest **zasada minimalnej częstości** (*minimum frequency rule*), która stanowi, że komórka tablicy jest uważana jako niebezpieczna, jeśli liczba jednostek w tej komórce jest mniejsza od zdefiniowanej odgórnie częstości granicznej (w przypadku statystyki publicznej w Polsce wynosi ona 3. Z kolei druga z zasad – reguła $(n, k)$ dominacji – stwierdza, że komórka obarczona jest ryzykiem pierwotnym, jeśli $n$ największych podmiotów gospodarczych w komórce tablicy reprezentuje więcej niż $k\%$ całkowitej wartości cechy ilościowej w komórce. Zasady te znajdują odzwierciedlenie w zapisach art. 38 ust. 2 Ustawy (z $k=3$ w pierwszym oraz $n=1$ i $k=75$ w drugim przypadku). Niejednokrotnie zapisy te utożsamiane są z definicją [tajemnicy statystycznej](dictionary00_2.qmd#term-t54), jednak taka interpretacja jest błędna – te zapisy to zasady, których stosowanie eliminuje bądź ogranicza ryzyko ujawnienia danych, które powinny być chronione – są to zatem metody [kontroli ujawniania danych statystycznych](dictionary00_2.qmd#term-t19).

Z ochroną tajemnicy statystycznej związane jest także pojęcie [„ujawnienia"](dictionary00_2.qmd#term-t56). Ujawnienie może nastąpić poprzez dostęp jednostek do danych statystycznych, np. znajdujących się w opublikowanych wynikach badań. Rozróżnia się trzy typy ujawnienia danych:

* identyfikacja, kiedy jednostka zostaje zidentyfikowana w zakresie danych chronionych, objętych tajemnicą statystyczną,
* ujawnienie atrybutu, kiedy na podstawie udostępnionych danych możliwe jest poznanie dodatkowej charakterystyki jednostki,
* ujawnienie poprzez wnioskowanie, jeżeli na podstawie publikowanych danych jest możliwe ustalenie szacunku dotyczącego charakterystyki podmiotu z większą dokładnością niż zakłada to publikacja.

Z pojęciem "ujawnienia" wiąże się nieodłącznie problem ryzyka ujawnienia, czyli prawdopodobieństwa tego, że dana jednostka pozna charakterystykę innej jednostki na podstawie udostępnionych danych, naruszając tym samym jej autonomię w zakresie prawa do ochrony danych. Obecnie już coraz bardziej powszechna jest wiedza, że najprostsza czynność polegająca na usunięciu bezpośrednich identyfikatorów jednostek, takich jak np. imię i nazwisko, numer PESEL, Numer Identyfikacji Podatkowej (NIP), etc. nie redukuje całkowicie prawdopodobieństwa identyfikacji. Współcześnie, w dobie wielu źródeł danych o znacznym rozmiarze i superkomputerów mogących analizować miliony kombinacji zmiennych, to o wiele za mało, a utrwalone w wieloletniej praktyce proste reguły ukrywania okazują się dalece niewystarczające. Dzieje się tak z uwagi na – zazwyczaj znaczną – liczbę zmiennych opisujących dane jednostki, co pociąga za sobą bardzo dużą liczbę możliwych kombinacji wariantów zmiennych wyrażonych na skali nominalnej lub porządkowej. Istnieje zatem spore ryzyko, że wystąpią wśród nich kombinacje unikatowe, w skrajnych sytuacjach odnoszące się tylko do jednej jednostki. Dlatego należy mieć świadomość, że każda publikacja danych statystycznych niesie za sobą pewne prawdopodobieństwo ujawnienia. Stąd ze strony krajowych urzędów statystycznych pojawiło się zapotrzebowanie na narzędzia i metody, które automatyzują proces [SDC](dictionary00_2.qmd#term-s16), pozwalają go parametryzować oraz raportować prawdopodobieństwo ujawnienia i stratę informacji. Takim remedium są metody kontroli ujawniania danych statystycznych, które zgodnie z definicją Komisji Europejskiej są określane jako narzędzia (metody, techniki) zastosowane na danych, które eliminują bądź redukują ryzyko ujawnienia informacji o analizowanych jednostkach. Należy je rozumieć jako kontrolę ryzyka ujawnienia informacji, które powinny być chronione tajemnicą statystyczną oraz poziomu straty informacji związanych z ukrywaniem lub zniekształcaniem danych wrażliwych.

Warto w tym miejscu zwrócić jeszcze uwagę na trzy aspekty związane z nomenklaturą stosowaną w zakresie tajemnicy statystycznej. Chodzi o sformułowania [„tajemnica pierwotna"](dictionary00_2.qmd#term-t52), [„tajemnica wtórna"](dictionary00_2.qmd#term-t55) oraz „nakładanie tajemnicy statystycznej”. Są to sformułowania powszechnie funkcjonujące w praktyce resortu statystyki i wynikające raczej z kilkudziesięcioletnich doświadczeń operacjonalizowania zapisów użytych w Ustawie, niż wprost z samych jej zapisów. Definicje pojęć *primary/secondary confidentiality*, które można byłoby przyjąć jako odpowiedniki pierwotnej i wtórnej tajemnicy statystycznej, można znaleźć w opracowaniach EUROSTATU (por. [@CODED] oraz [@hundepool2010handbook]). Dotyczą one danych w komórkach tablic statystycznych, których opublikowanie pozwoliłoby na ujawnienie atrybutów jednostek. Jako dwie główne przyczyny ryzyka ujawnienia atrybutów wskazuje się zbyt niską liczebność jednostek w komórce tablicy, bądź dominację jednej lub dwóch jednostek w komórce. Z pojęciami *primary/secondary confidentiality* wiążą się także pojęcia *primary/secondary suppression* (pierwotnego i wtórnego ukrywania komórek) - oznaczjące techniki SDC, które mają zastosowanie w przypadku wystąpienia ryzyka ujawnienia tak zdefiniowanej pierwotnej i wtórnej tajemnicy statystycznej. Należy bowiem zauważyć, że „tajemnica pierwotna” oraz „tajemnica wtórna” są to zmodyfikowane polskie tłumaczenia pierwotnego i wtórnego ukrywania komórek w tablicach kontyngencji (ang. *primary suppression, secondary suppression*). Natomiast sformułowanie „nakładanie tajemnicy statystycznej” stosowane jest w celu opisania technicznej czynności zaznaczenia tych przekrojów (komórek tablicy statystycznej, agregacji), które powinny być objęte ochroną ze względu na tajemnicę statystyczną. Należy zaznaczyć, że czynność ta wykonywana jest na tych etapach procesu produkcji statystycznej, które poprzedzają etap udostępniania. W tym przypadku Zespół sugeruje stosować sformułowanie „ukrywanie (pierwotne lub wtórne) przekrojów objętych tajemnicą statystyczną”. Uznając zatem pewien zwyczaj istniejący w resorcie statystyki, jeszcze jednym celem niniejszego *Przewodnika* będzie zatem promowanie właściwych określeń związanych z tajemnicą statystyczną i metodami kontroli ujawniania danych statystycznych.

:::
