# [Podstawy prawne tajemnicy statystycznej]{#sec-law}

::: justify
Z punktu widzenia prawnego, **tajemnica** to określona przez przepisy wiadomość, informacja, dane, których poznanie lub ujawnienie jest zakazane przez prawo. Punktem wyjścia do stosowania tajemnicy statystycznej jest właściwe i efektywne stosowanie uregulowań formalnoprawnych, zarówno krajowych, unijnych, jak i międzynarodowych   (np. OECD, ONZ), bowiem to na nich powinien opierać się każdy zorganizowany system statystyczny.

**Ustawa z dnia 29 czerwca 1995 r. o statystyce publicznej**  
Tajemnica statystyczna jest pojęciem wprowadzonym do prawa polskiego art. 10 Ustawy, który stanowi, że ***Dane jednostkowe identyfikowalne zebrane w badaniach statystycznych podlegają bezwzględnej ochronie. Dane te mogą być wykorzystywane wyłącznie do opracowań, zestawień i analiz statystycznych oraz do tworzenia przez Prezesa Głównego Urzędu Statystycznego operatu do badań statystycznych; udostępnianie lub wykorzystywanie tych danych dla innych niż podane w ustawie celów jest zabronione (tajemnica statystyczna).***

Konstrukcja tajemnicy statystycznej opiera się zasadniczo na trzech pojęciach zdefiniowanych w art. 2 Ustawy:

* **dane jednostkowe identyfikowalne** (art. 2 pkt 8a Ustawy), które oznaczają *dane statystyczne zawierające informacje dotyczące konkretnego podmiotu gospodarki narodowej albo osoby fizycznej, identyfikujące bezpośrednio ten podmiot albo osobę według nazwy, imienia i nazwiska, adresu lub publicznie dostępnego numeru identyfikacyjnego oraz pozwalające na pośrednią identyfikację tego podmiotu albo osoby z użyciem innych środków niż środki pozwalające na bezpośrednią identyfikację, z wyłączeniem środków wymagających nadmiernych kosztów, czasu lub działań*;
* **badania statystyczne** (art. 2 pkt 2 Ustawy) zdefiniowane jako *zbieranie, gromadzenie i opracowywanie danych statystycznych oraz ogłaszanie i udostępnianie wyników dokonanych obliczeń, opracowań i analiz, w tym podstawowych wielkości i wskaźników*;
* **dane statystyczne** (art. 2 pkt 1a Ustawy), które oznaczają *dane dotyczące zjawisk, zdarzeń, obiektów i działalności podmiotów gospodarki narodowej oraz życia i sytuacji osób fizycznych, w tym dane osobowe, pozyskane bezpośrednio od respondentów albo z systemów informacyjnych administracji publicznej, rejestrów urzędowych lub niepublicznych systemów informacyjnych, od momentu ich zebrania na potrzeby wykonywania zadań statystyki publicznej*.

Przepisy Ustawy opierają system statystyki publicznej na zaufaniu między służbami statystycznymi odpowiedzialnymi za zbieranie i opracowywanie informacji a respondentami. Podejście do tajemnicy statystycznej i samej statystyki publicznej ewoluowało wraz z demokratyzacją życia społecznego oraz wdrażaniem szeregu uregulowań wynikających z umów międzynarodowych. W stosunku do uprzednio obowiązującej ustawy z dnia 26 lutego 1982 r. o statystyce państwowej^[Dz.U. z 1989 r. Nr 40, poz. 221 z późn. zm.], Ustawa z 1995 r. wprowadziła rozwiązania właściwe dla społeczeństw   demokratycznych, łagodząc przymus administracyjny w wypełnianiu obowiązków statystycznych na rzecz społecznego wymiaru statystyki publicznej i postrzegania statystyki jako dobra publicznego. Nawet w ustawie z dnia 26 lutego 1982 r. o statystyce państwowej, w brzmieniu pierwotnym art. 25 dane statystyczne podlegały ochronie: *Publikowanie wyników badań statystycznych oraz dostęp do informacji statystycznych podlegają ograniczeniom wynikającym z ochrony tajemnicy państwowej i gospodarczej oraz sfery praw osobistych obywateli*.

Statystyka publiczna (w tym tajemnica statystyczna) funkcjonuje w krajowym porządku w wielu aktach prawnych, jednak podstawy jej funkcjonowania określone są Ustawą.

Rola i cele statystyki publicznej określa art. 3 Ustawy: *Statystyka publiczna zapewnia rzetelne, obiektywne i systematyczne informowanie społeczeństwa, organów państwa i administracji publicznej oraz podmiotów gospodarki narodowej o sytuacji ekonomicznej, demograficznej, społecznej oraz środowiska naturalnego*. Badania statystyki publicznej mogą dotyczyć każdej dziedziny życia społecznego i gospodarczego oraz występujących w nim zjawisk dających się obserwować i analizować z wykorzystaniem metod statystycznych przy uwzględnieniu celowości, niezbędności oraz społecznej użyteczności danych (art. 4 Ustawy). Służby statystyki publicznej zbierają, gromadzą i opracowują dane od podmiotów gospodarki narodowej i o tych podmiotach oraz ich działalności, a także dane od osób fizycznych i o tych osobach, ich życiu i sytuacji, oraz dane dotyczące zjawisk, zdarzeń i obiektów, przechowują, łączą pozyskane dane i wtórnie je wykorzystują w celu realizacji zadań określonych w Ustawie (art. 5 ust. 1 Ustawy).

W art. 6 ust. 2 Ustawy wprowadzono przepis mający zapewnić możliwość prawidłowego wykonywania zadań statystyki publicznej, stanowiąc, że: *Badania statystyczne mogą być prowadzone na zasadzie obowiązku albo udziału dobrowolnego*. W przypadku, gdy badania statystyczne prowadzone są z udziałem osób fizycznych, z wyłączeniem osób fizycznych prowadzących działalność gospodarczą i spisów powszechnych, są prowadzone na zasadzie udziału dobrowolnego (art. 6 ust. 3 i 4 Ustawy). Udział w badaniach statystycznych, dotyczących działalności gospodarczej prowadzonej przez osoby fizyczne, jest obowiązkowy (art. 6 ust. 4 Ustawy).

W obowiązującym porządku prawnym szczególne miejsce zajmuje obejmowanie tajemnicą statystyczną danych osób fizycznych biorących udział w badaniach statystycznych.  Zasady ustanowione w Ustawie głównie osadzone są na normach określonych w rozporządzeniu Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (ogólne rozporządzenie o ochronie danych)^[Dz. Urz. UE L 119 z 04.05.2016, str. 1, z późn. zm.], zwanego dalej Rozporządzeniem RODO lub RODO, w powiązaniu z normami wywiedzionymi z Rozporządzenia Parlamentu Europejskiego i Rady (WE) Nr 223/2009 z dnia 11 marca 2009 r. w sprawie statystyki europejskiej oraz uchylające rozporządzenie Parlamentu Europejskiego i Rady (WE, Euratom) nr 1101/2008 w sprawie przekazywania do Urzędu Statystycznego Wspólnot Europejskich danych statystycznych objętych zasadą poufności, rozporządzenie Rady (WE) – nr 322/97 w sprawie statystyk Wspólnoty oraz decyzję Rady 89/382/EWG, Euratom w sprawie ustanowienia Komitetu ds. Programów Statystycznych Wspólnot Europejskich – dalej Rozporządzenie Nr 223/2009.

Zagadnieniu przetwarzania danych osobowych dla celów statystycznych poświęcony został rozdział 4a Ustawy (obejmuje art. 35a-h), poprzedzony wyjątkiem opisanym w art. 8 Ustawy, który zawiera bezwzględny zakaz zbierania na zasadzie obowiązku w badaniach statystycznych prowadzonych z udziałem osób fizycznych danych osobowych, o których mowa w art. 9 ust. 1 i art. 10 RODO tj. *danych osobowych ujawniających pochodzenie rasowe lub etniczne, poglądy polityczne, przekonania religijne lub światopoglądowe, przynależność do związków zawodowych oraz przetwarzania danych genetycznych, danych biometrycznych w celu jednoznacznego zidentyfikowania osoby fizycznej lub danych dotyczących zdrowia, seksualności lub orientacji seksualnej tej osoby oraz danych osobowych dotyczących wyroków skazujących oraz czynów zabronionych lub powiązanych środków bezpieczeństwa*.

Należy zwrócić przy tym uwagę, że zakaz przetwarzania powyższych danych dotyczy tylko zbierania danych osobowych na zasadzie obowiązku w badaniach statystycznych prowadzonych z udziałem osób fizycznych, natomiast nie dotyczy przetwarzania danych osobowych zbieranych przez służby statystyki publicznej od respondentów na zasadzie dobrowolności oraz danych pozyskiwanych z systemów informacyjnych administracji publicznej, rejestrów urzędowych i niepublicznych systemów informacyjnych, przy jednoczesnym zapewnieniu gwarancji ich pełnej ochrony na zasadach określonych w Ustawie (art. 35c ust. 3 Ustawy).   

W zakresie nakładania tajemnicy statystycznej rozdział ten wyraźnie wzmacnia i doprecyzowuje uprawnienia i obowiązki służb statystyki publicznej względem danych osób fizycznych zebranych w badaniach statystycznych i ich bezwzględnej ochrony poprzez bezpośrednie wskazanie objęcia danych osobowych tajemnicą statystyczną od momentu ich zebrania (art. 35aa Ustawy: *Dane osobowe od momentu ich zebrania bezpośrednio od respondentów albo z systemów informacyjnych administracji publicznej i rejestrów urzędowych lub niepublicznych systemów informacyjnych na potrzeby wykonywania zadań określonych w ustawie stają się danymi statystycznymi i objęte są tajemnicą statystyczną z wyłączeniem informacji zawartych w krajowym rejestrze urzędowym podmiotów gospodarki narodowej*.).

Dodatkowym wzmocnieniem świadomości co do tajemnicy statystycznej i praw wśród osób fizycznych, które udzielają bezpośrednio odpowiedzi w badaniach statystycznych jest rozwiązanie przyjęte w art. 35h ust. 3 w związku z art. 6 ust. 5 Ustawy. W sytuacji zbierania danych osobowych od osoby, której dane dotyczą, przed rozpoczęciem badania niezbędne jest przekazanie informacji istotnych z punktu widzenia procedury zbierania danych i ich dalszego przetwarzania (art. 13 ust. 1 i 2 RODO) razem z informacjami o podstawie prawnej badania, celu badania i gwarancjach zachowania tajemnicy, o której mowa w art. 10, oraz czy udział w badaniu jest obowiązkowy czy dobrowolny.

Jednocześnie w rozdziale 4a Ustawy zawarto cele przetwarzania danych osobowych (art. 35a ust. 1 Ustawy), zakres przetwarzanych danych osobowych (art. 35b ust. 1 Ustawy) oraz źródła przetwarzanych danych (art. 35c ust. 1 Ustawy).

W art. 35h ust. 1 Ustawy ograniczono prawa osób fizycznych poprzez wprowadzenie zastrzeżenia, że do przetwarzania danych osobowych w celu wykonywania zadań przez służby statystyki publicznej nie stosuje się następujących przepisów Rozporządzenia RODO dotyczących:

*	art. 15 - prawa do informacji, czy przetwarzane są dane osobowe tej osoby i uzyskania do nich dostępu,
*	art. 16 – prawa do sprostowania danych, 
*	art. 18 – prawa do ograniczenia przetwarzania,
*	art. 21 – prawa do wniesienia sprzeciwu wobec przetwarzania dotyczących jej danych osobowych. 

W art. 35d Ustawy wprowadzono postanowienia określające narzędzie wzmacniające ochronę danych osobowych i wspomagające tajemnicę statystyczną. Pseudonimizacja danych to pojęcie wprowadzone do prawa za pomocą art. 4 pkt 5 Rozporządzenia RODO. Pseudonimizacja jest odwracalnym procesem, który jest przeprowadzany w celu ograniczenia możliwości identyfikacji danej osoby. Dane poddane procesowi pseudonimizacji dalej podlegają ochronie prawnej. W zakresie statystyki publicznej *dane osobowe po ich zebraniu przez służby statystyki publicznej, jeżeli pozwala na to cel ich przetwarzania, są **pseudonimizowane***. Sposób i tryb pseudonimizacji danych osobowych określa, w drodze zarządzenia, Prezes Głównego Urzędu Statystycznego.

Z tajemnicą statystyczną związane jest udostępnianie i przechowywanie informacji statystycznych, o czym stanowi rozdział 5 Ustawy (art. 36 – art. 39). 

Prowadzący badania statystyczne statystyki publicznej obowiązani są ogłaszać, udostępniać i rozpowszechniać wynikowe informacje statystyczne z zachowaniem przepisów o tajemnicy statystycznej (art. 14 Ustawy)^[Zob. również art. 21 Ustawy.]. Wynikowe informacje statystyczne są powszechnie dostępne, a ich rodzaje, formy i terminy ich udostępnienia są ustalane w Rozporządzeniu Rady Ministrów dotyczącego programu badań statystycznych statystyki publicznej.

Konsekwentnie do brzmienia definicji tajemnicy statystycznej, zawartej w art. 10 Ustawy, wprowadzono w zakresie publikowania i udostępniania, zgodnie z art. 38 Ustawy, zakaz publikowania i udostępniania danych jednostkowych identyfikowalnych uzyskanych w badaniach statystycznych. Dodatkowo, w celu  zapewnienia zachowania poufności w rozumieniu przepisów wspólnotowych oraz tajemnicy statystycznej w rozumieniu prawa krajowego, przy publikacji i udostępnianiu uzyskanych w badaniu statystycznym danych, których ochrona powinna być wzmocniona, doprecyzowano zakres objęcia tajemnicą statystyczną, wprowadzając w art. 38 ust. 2 Ustawy poniższy zakaz.

**Zakaz dotyczy publikowania i udostępniania danych umożliwiających powiązanie i zidentyfikowanie konkretnej osoby fizycznej oraz informacji i danych statystycznych charakteryzujących wyniki ekonomiczno-finansowe podmiotów gospodarki narodowej prowadzących działalność gospodarczą, jeżeli na daną agregację składa się mniej niż trzy podmioty lub udział jednego podmiotu w określonym zestawieniu jest większy niż trzy czwarte całości.**

Inne zastrzeżenie w kwestii udostępniania danych dotyczy operatu do badań statystycznych (OBS). Operat to wykaz objętych badaniami statystycznymi podmiotów gospodarki narodowej, osób fizycznych oraz innych podmiotów podlegających obserwacji statystycznej uporządkowany według określonych cech, zawierający dane jednostkowe wraz z ich identyfikacją teleadresową (art. 2 pkt 8 Ustawy).

W art. 39c ust. 2 Ustawy, wskazano ograniczenia w udostępnianiu (objęcie tajemnicą statystyczną) danych gromadzonych w OBS. W przypadku badania statystycznego prowadzonego przez inny wskazany naczelny lub centralny organ administracji państwowej albo Narodowy Bank Polski, o ile badanie to wymaga wiedzy specjalistycznej, którą dysponuje ten organ, albo jeżeli jest on w posiadaniu danych zgromadzonych w innym celu, Prezes Głównego Urzędu Statystycznego, na wniosek prowadzącego badanie udostępnia mu z OBS dane adresowe podmiotów wylosowanych lub wybranych na podstawie wskazanych przez niego cech, z wyłączeniem danych adresowych osób fizycznych nieprowadzących działalności gospodarczej.

Istotnym dla zachowania tajemnicy statystycznej jest przypisanie Prezesowi Głównego Urzędu Statystycznego obowiązku zapewnienia przechowywania zgromadzonych danych zgodnie z zasadami określonymi w Ustawie (art. 39 Ustawy). 

Ochronie tajemnicy statystycznej służy również art. 12 Ustawy, według którego: *Pracownicy służb statystyki publicznej, rachmistrze spisowi, ankieterzy statystyczni oraz inne osoby wykonujące czynności w imieniu i na rzecz statystyki publicznej, mający bezpośredni dostęp do danych indywidualnych i danych osobowych, są obowiązani do bezwzględnego przestrzegania tajemnicy statystycznej i mogą być dopuszczeni do wykonywania tych czynności po złożeniu w urzędzie statystycznym albo innej jednostce organizacyjnej służb statystyki publicznej pisemnego przyrzeczenia*.

Obowiązek respektowania zasady ochrony poufności statystycznych danych jednostkowych (tj. umożliwiających identyfikację respondenta) został nadto obwarowany sankcją karną, co wskazuje na znaczenie prawne tajemnicy statystycznej.

W art. 54 Ustawy naruszenie tajemnicy statystycznej spenalizowane zostało karą do trzech lat pozbawienia wolności.

W art. 55 Ustawy ustanowiono zaś przestępstwo polegające na wykorzystaniu w celu osiągnięcia korzyści majątkowej lub osobistej danych statystycznych, z którymi sprawca zapoznał się w związku z wykonywaniem pracy lub odpowiedniego zlecenia, zagrożone sankcją do 5 lat pozbawienia wolności.

Zastrzec należy, że tajemnica statystyczna jako obowiązek ustawowy, nie może być postrzegana jedynie przez pryzmat samej definicji zawartej w art. 10 Ustawy, bowiem na jej charakter prawny wpływają nie tylko przepisy prawa krajowego na czele z ustawą zasadniczą (Konstytucją Rzeczypospolitej Polskiej), ale też normy europejskie i miedzynarodowe, które w związku z art. 91 ust. 3 Konstytucji Rzeczypospolitej Polskiej stają elementem prawa krajowego^[Konstytucja RP art. 91 ust. 3 Jeżeli wynika to z ratyfikowanej przez Rzeczpospolitą Polską umowy konstytuującej organizację międzynarodową, prawo przez nią stanowione jest stosowane bezpośrednio, mając pierwszeństwo w przypadku kolizji z ustawami.].

**Konstytucja Rzeczypospolitej Polskiej z dnia 2 kwietnia 1997 r.**^[Dz.U. z 1997 r. Nr 78, poz. 483.]

*	**art. 2 Konstytucji RP, który stanowi, że Rzeczpospolita jest demokratycznym państwem prawnym.**

Klauzula państwa prawnego wynikająca z art. 2 Konstytucji RP, dotyczy między innymi zasady zaufania obywatela do państwa. Zasada zaufania uznana została za fundament państwa prawnego. Według Trybunału Konstytucyjnego zasada zaufania obywateli do państwa i stanowionego przez nie prawa, nazywana także zasadą lojalności państwa względem obywateli i podmiotów, jest jedną z najważniejszych zasad pochodnych, wynikających z zasady demokratycznego państwa prawnego^[zob. np. wyr. TK z 20.12.1999 r., K 4/99, OTK 1999, Nr 7, poz. 165.].

W kontekście tajemnicy statystycznej konstytucyjna zasada zaufania do państwa i stanowionego przez nie prawa polega na zagwarantowaniu każdemu respondentowi pewności, że jego dane nie będą zbierane, gromadzone, przetwarzane i udostępniane na warunkach innych aniżeli wynika to z Ustawy tj. z zachowaniem tajemnicy statystycznej, skoro warunki zapewnienia tajemnicy zostały określone w Ustawie. 

*	**art. 7 Konstytucji RP**, w myśl którego organy władzy publicznej działają na podstawie i w granicach prawa. 
W najbardziej ogólnym ujęciu w art. 7 Konstytucji RP ustanowiono konstytucyjny nakaz działania organów władzy publicznej na podstawie i w granicach prawa. Kompetencji organów nie można domniemywać, a co nie jest im dozwolone, jest zabronione. To, co jest nakazane, powinno być zrealizowane. W kontekście art. 7 Konstytucji RP na szczególną uwagę zasługują przepisy dotyczące przestrzegania tajemnicy statystycznej (art. 10, art. 39, art. 39a, art. 39c Ustawy).  
*	**art. 31 ust. 2 i 3 Konstytucji RP**, który stanowi, że *ograniczenia w zakresie korzystania z konstytucyjnych wolności i praw mogą być ustanawiane tylko w ustawie i tylko wtedy, gdy są konieczne w demokratycznym państwie dla jego bezpieczeństwa lub porządku publicznego, bądź dla ochrony środowiska, zdrowia i moralności publicznej, albo wolności i praw innych osób. Ograniczenia te nie mogą naruszać istoty wolności i praw*.

Przykładem ograniczeń może być obowiązek uczestniczenia obywateli w spisie powszechnym na podstawie ustawy spisowej (art. 9 Ustawy), co nie zmienia faktu, że obywatel ma prawo oczekiwać od państwa proporcjonalności działań oraz stosownej ochrony.  

* **art. 47 Konstytucji RP**, w myśl którego każdy ma prawo do ochrony prawnej życia prywatnego i rodzinnego. 

Nie ulega wątpliwości, że z istoty gwarancji określonej w art. 47 Konstytucji RP, z jej ścisłego związku z godnością człowieka oraz z użytego pojęcia "każdy" wynika, że dotyczy ona wszystkich osób fizycznych^[tak np. Banaszak B., , Konstytucja Rzeczypospolitej Polskiej. Komentarz, Warszawa, 2012, komentarz do art. 47, nb. 1. ]. 

**Życie prywatne** to przymioty, wewnętrzne przeżycia osobiste (jednostkowe) człowieka i ich oceny, refleksje dotyczące wydarzeń zewnętrznych i jego wrażenia zmysłowe, a także stan zdrowia^[wyr. TK z 19.05.1998 r., U 5/97, OTK 1998, Nr 4, poz. 46.] oraz sytuacja majątkowa^[orz. TK z 24.06.1997 r., K 21/96, OTK 1997, Nr 2, poz. 23.]. Nie są one w założeniu przeznaczone do upowszechniania i sam zainteresowany decyduje o kręgu osób, z którymi zechce się nimi podzielić. Samo życie prywatne jako element prawa do prywatności zaczęło dopiero niedawno odgrywać poważniejszą rolę w regulacjach konstytucyjnych i orzecznictwie sądowym. Od dłuższego czasu wywierało jednak coraz silniejszy wpływ na pozycję jednostki we współczesnych państwach demokratycznych. Tak rozumiane życie prywatne odnosi się generalnie do życia: osobistego, towarzyskiego, nienaruszalności mieszkania, tajemnicy korespondencji i ochrony informacji dotyczących danej osoby. 

**Życie rodzinne**, aczkolwiek związane z prywatnym, dotyczy już szerszej sfery przeżyć i zdarzeń związanych z rodziną pojętą nie tylko jako zespół osób prowadzących z danym człowiekiem wspólne gospodarstwo domowe. 

Ustawa tę ochronę ogranicza, co jest dopuszczalne, jednakże pod warunkiem zapewnienia anonimowości ingerencji dzięki tajemnicy statystycznej.

W tym zakresie Ustawa gwarantuje respondentom prawa oparte na dobrowolności uczestniczenia w badaniach statystycznych (art. 6 ust. 3 i 5 w związku z art. 10 oraz art. 8 Ustawy) z wyłączeniem spisów powszechnych (art. 9 Ustawy) oraz pewność, że dane podane w badaniach będą objęte bezwzględną tajemnicą statystyczną.  

Jako pewne uproszczenie należy jednak uznać pogląd, jakoby tylko osoby fizyczne były zdolne do posiadania życia prywatnego, czci i dobrego imienia w rozumieniu wskazanego przepisu. 

Gwarancje art. 47 Konstytucji RP są bowiem rozciągane również na jednostki organizacyjne. Już w pierwszym wyroku poświęconym prawu do prywatności TK, oceniając zgodność z Konstytucją RP ingerencji w tajemnicę bankową, przyznawał *każdemu podatnikowi prowadzącemu działalność gospodarczą* prawo do pewnej prywatności tej działalności, o ile nie ma ona na celu ukrycia działalności przestępczej lub uchylenia się od określonych zobowiązań publiczno-prawnych^[orz. TK z 24.06.1997 r., K 21/96, OTK 1997, Nr 2, poz. 23.]. Pojęcie podatnika obejmuje zarówno osoby fizyczne jak i podmioty niebędące osobami fizycznymi.

* **art. 51 ust. 2 Konstytucji RP**, w myśl którego władze publiczne nie mogą pozyskiwać, gromadzić i udostępniać innych informacji o obywatelach niż niezbędne w demokratycznym państwie prawnym. 
Zakres podmiotowy gwarantowanego w art. 51 ust. 2 Konstytucji RP prawa dotyczy obywateli – z czego można wywieść wniosek, iż władze publiczne mogą przetwarzać informacje dotyczące innych osób i dane poddane przetworzeniu nie muszą spełniać jednocześnie warunku niezbędności w demokratycznym państwie prawnym (np. uchodźcy, cudzoziemcy). 

Sformułowanie *informacje o obywatelach (...) niezbędne w demokratycznym państwie prawnym* można określić jako te dane, które umożliwiają normalne funkcjonowanie jednostki w zorganizowanym w państwo społeczeństwie. Zaś z punktu widzenia organów władz publicznych za **niezbędną** uznać należy każdą informację, bez posiadania której nie będą one zdolne do podjęcia (czy zakończenia) działań w ramach przyznanych im kompetencji (np. art. 4 ust. 2 oraz rozdziały 2 i 4a Ustawy).

Przetwarzanie i gromadzenie informacji o osobach spełni warunek konstytucyjności, jeżeli: nie powstaje ryzyko wykorzystywania tych danych także do celów pozaustawowych lub celów pozaumownych, gdy chodzi o umowę międzynarodową, której stroną jest RP. Informacje powinny być chronione przed niepowołanym dostępem lub przed wykorzystywaniem w celach niezgodnych z prawem i pierwotnym celem ich pozyskania, a standardy ich przetwarzania powinny być zgodne z przepisami prawa. 

W ocenie TK nie jest zakazane zbieranie informacji, nawet bez wiedzy osoby, której te informacje dotyczą, aczkolwiek sposób i zakres pozyskiwanych informacji musi sprostać testowi *konieczności w demokratycznym państwie prawnym*^[orz. z 23.06.2009 r., K 54/07, OTK 2009, Nr 6A, poz. 86.]. Usprawiedliwione jest stosowanie środków niezbędnych w tym sensie, że chronią wartości istotne w państwie demokratycznym, i to w sposób (bądź w stopniu), który nie mógłby zostać osiągnięty przy stosowaniu innych środków (np. art. 5a Ustawy).

Art. 51 ust. 2 Konstytucji RP wprowadza powołany wymóg niezbędności. Pozyskanie (zbieranie) informacji o osobie jest działaniem państwa, które jest wyłomem w sferze wolności jednostki, a takie działanie musi podlegać ścisłej kontroli pod względem proporcjonalności ograniczeń, zakazu naruszania istoty prawa, a także określoności normy kompetencyjnej zezwalającej na pozyskiwanie informacji o obywatelach (art. 2, art. 31 ust. 2, art. 51 Konstytucji RP). Niezbędność musi być jednak rozumiana ściśle, a więc dane osobowe muszą być warunkiem sine qua non wykonania obowiązku ciążącego na władzy publicznej. 

**Prawo Unii Europejskiej**

Akty prawne wydawane na poziomie UE wpływają na krajowy porządek prawny państw członkowskich  zależnie od ich charakteru – albo wchodząc do niego wprost albo też wymuszając podjęcie działań prawnych, w tym krajowych, w nich określonych. Zasady ogólnie nakreślające charakter poszczególnych narzędzi prawnych UE zawiera art. 288 Traktatu o funkcjonowaniu Unii Europejskiej^[Art. 288 TFUE W celu wykonania kompetencji Unii instytucje przyjmują rozporządzenia, dyrektywy, decyzje, zalecenia i opinie. Rozporządzenie ma zasięg ogólny. Wiąże w całości i jest bezpośrednio stosowane we wszystkich Państwach Członkowskich.
Dyrektywa wiąże każde Państwo Członkowskie, do którego jest kierowana, w odniesieniu do rezultatu, który ma być osiągnięty, pozostawia jednak organom krajowym swobodę wyboru formy i środków. 
Decyzja wiąże w całości. Decyzja, która wskazuje adresatów, wiąże tylko tych adresatów. 
Zalecenia i opinie nie mają mocy wiążącej.
].

Instrumentem najgłębszej ingerencji prawodawcy wspólnotowego w porządki prawne państw członkowskich są rozporządzenia. Mają one zasięg ogólny, generalny  . Obowiązują w całości i są stosowane bezpośrednio we wszystkich państwach członkowskich. 

Dla Trybunału Sprawiedliwości Unii Europejskiej „zasięg ogólny” jest równoznaczny z normatywnością aktu, co potwierdza jego status, jako źródła prawa wspólnotowego. Oznacza to, że państwa członkowskie nie mogą podejmować żadnych środków krajowych ustawodawczych, które byłyby sprzeczne z rozporządzeniem. Związanie rozporządzeniem staje się aktualne z chwilą jego wejścia w życie.

Cechą swoistą rozporządzeń jest to, że są one bezpośrednio stosowalne. Oznacza to, że akty te ze swej natury stają się częścią krajowych systemów prawnych bez potrzeby dokonywania jakichkolwiek czynności transpozycyjnych i wywierają skutki bezpośrednie w stosunku do jednostek (tak jak omawiane niżej Rozporządzenie Nr 223/2009 i Rozporządzenie RODO). Jeśli unijny akt prawnych upoważnia państwa członkowskie do podejmowania środków wykonawczych, to sposób wykonywania ma określać prawo publiczne państwa członkowskiego.   

Mimo, że kluczowym dla statystyki europejskiej jest rozporządzenie 223/2009 kwestię z nią związane regulują też inne unijne akty prawne, odnoszące się również do zasady poufności (np. wspomniane wcześniej RODO). 

**Rozporządzenie Parlamentu Europejskiego i Rady (WE) Nr 223/2009 z dnia 11 marca 2009 r. w sprawie statystyki europejskiej oraz uchylające rozporządzenie Parlamentu Europejskiego i Rady (WE, Euratom) nr 1101/2008 w sprawie przekazywania do Urzędu Statystycznego Wspólnot Europejskich danych statystycznych objętych zasadą poufności, rozporządzenie Rady (WE) – nr 322/97 w sprawie statystyk Wspólnoty oraz decyzję Rady 89/382/EWG, Euratom w sprawie ustanowienia Komitetu ds. Programów Statystycznych Wspólnot Europejskich**^[Dz.Urz. UE L 2009 Nr 87, str. 164.]– Rozporządzenie Nr 223/2009.

Zgodnie z Traktatem ustanawiającym Wspólnotę Europejską, a w szczególności z jego art. 285 ust. 2, Polska jako członek Unii Europejskiej przyjęła na siebie zobowiązanie stosowania praw obowiązujących we Wspólnocie, w tym bezwzględnego przestrzegania tajemnicy statystycznej.

W art. 3 Rozporządzenia Nr 223/2009 zawarto kluczowe w zakresie poufności danych statystycznych definicje: 

*	**dane statystyczne**: ilościowe i jakościowe, zagregowane i reprezentatywne informacje opisujące złożone zjawisko w rozpatrywanej populacji, 
*	**opracowywanie danych**: działania zmierzające do utworzenia, usprawnienia i udoskonalenia metod, standardów i procedur statystycznych stosowanych przy tworzeniu i rozpowszechnianiu danych statystycznych, jak również do projektowania nowych danych i wskaźników, 
*	**tworzenie informacji statystycznych**: wszelka działalność związana ze zbieraniem, przechowywaniem, przetwarzaniem, zestawianiem i analizą, niezbędnymi do zestawienia danych statystycznych, 
*	**rozpowszechnianie danych**: działanie, którego celem jest udostępnianie danych statystycznych i analiz statystycznych użytkownikom, 
*	**zbieranie danych**: badania oraz wszelkie inne formy pozyskiwania informacji z różnych źródeł, w tym ze źródeł administracyjnych, 
*	**jednostka statystyczna**: podstawowa jednostka objęta obserwacją – mianowicie osoba fizyczna, gospodarstwo domowe, podmiot gospodarczy czy inny podmiot – do której odnoszą się dane, 
*	**dane poufne**: dane umożliwiające bezpośrednią lub pośrednią identyfikację jednostek statystycznych, co skutkuje ujawnieniem informacji indywidualnych. Aby określić, czy możliwa jest identyfikacja danej jednostki statystycznej, należy wziąć pod uwagę wszystkie przewidywalne środki, które mogą być użyte przez osobę trzecią do zidentyfikowania jednostki statystycznej, 
*	**wykorzystanie do celów statystycznych**: wykorzystanie wyłącznie do celów opracowywania i tworzenia wyników oraz analiz statystycznych, 
*	**identyfikacja bezpośrednia**: identyfikacja jednostki statystycznej według jej nazwy lub adresu lub według publicznie dostępnego numeru identyfikacyjnego,
*	**identyfikacja pośrednia**: identyfikacja jednostki statystycznej z użyciem wszelkich innych środków niż środki identyfikacji bezpośredniej. 

Kwestia poufności danych statystycznych została doprecyzowana w rozdziale piątym Rozporządzenia Nr 223/2009. Stanowi on, że krajowe   urzędy statystyczne i inne organy odpowiedzialne za opracowywanie, tworzenie i rozpowszechnianie statystyki europejskiej oraz Eurostat dla zapewnienia, że poufne dane są wykorzystywane wyłącznie do celów statystycznych, a także w celu zapobieżenia ich bezprawnemu ujawnieniu, stosują następujące zasady i środki:

* wykorzystują poufne dane uzyskane wyłącznie do celów tworzenia statystyki europejskiej wyłącznie do celów statystycznych, chyba że jednostka statystyczna wyrazi jednoznaczną zgodę na wykorzystanie tych danych do innych celów - art. 20 ust. 1 Rozporządzenia Nr 223/2009,
*	wyniki statystyczne, dzięki którym możliwa jest identyfikacja jednostki statystycznej, mogą być rozpowszechniane w następujących wyjątkowych przypadkach (art. 20 ust. 3 Rozporządzenia Nr   223/2009):
    - jeżeli szczególne warunki i tryb zostały określone w akcie prawnym Parlamentu Europejskiego i Rady działających zgodnie z art. 251 Traktatu, a wyniki statystyczne wprowadzane są w taki sposób, że ich rozpowszechnianie nie stanowi uszczerbku dla poufności informacji statystycznych,
    - lub jeżeli jednostka statystyczna w jednoznaczny sposób wyraziła zgodę na ujawnienie tych danych,
*	w zakresie odpowiednich kompetencji podejmują wszelkie niezbędne środki regulacyjne, administracyjne, techniczne i organizacyjne działania w celu zapewnienia ochrony fizycznej i logicznej poufnych danych (kontrola ujawniania danych statystycznych)^[Pojęcie kontrola ujawniania danych statystycznych zostało formalnie zdefiniowane dopiero  w art. 2 Rozporządzenia Komisji (UE) Nr 1151/2010 z dnia 8 grudnia 2010 r. w sprawie wykonania rozporządzenia Parlamentu Europejskiego i Rady (WE) nr 763/2008 w sprawie spisów powszechnych ludności i mieszkań w odniesieniu do ustaleń dotyczących raportów jakości i ich struktury oraz formatu technicznego przekazywania danych (Dz.Urz. UE L Nr 324, str. 1). Według tego rozporządzenia kontrola ujawniania danych statystycznych oznacza metody i procesy zastosowane w celu zminimalizowania ryzyka ujawnienia informacji na temat poszczególnych jednostek statystycznych, przy jednoczesnym udostępnianiu jak największej ilości informacji statystycznych.] – art. 20 ust. 4 Rozporządzenia Nr 223/2009,
*	stosują wszelkie środki konieczne do zapewnienia harmonizacji zasad i wytycznych dotyczących fizycznej i logicznej ochrony poufnych danych - art. 20 ust. 4 Rozporządzenia Nr 223/2009,
*	urzędnicy i inny personel, mający dostęp do poufnych danych, obowiązani są przestrzegać wymogu poufności nawet po zakończeniu pełnienia swoich funkcji - art. 20 ust. 5 Rozporządzenia Nr 223/2009.

Rozporządzenie przewiduje możliwość przyznawania prawa dostępu do poufnych danych pracownikom naukowym   prowadzącym analizy statystyczne do celów prowadzonych badań - art. 23 Rozporządzenia Nr 223/2009. Warunkiem przyznania dostępu do badań jest tylko pośrednia identyfikacja jednostek statystycznych, uzyskiwana w praktyce poprzez pozbawienie jednostkowych cech umożliwaiących bezpośrednie zidentyfikowanie osób, których dane dotyczą np. imię, nazwisko, numer identyfikacyjny ewidencji ludności, adres zamieszkania. Również w tej sytuacji winny być podjęte działania uniemożliwiające pośrednią identyfikację jednostki statystycznej.  Należy również zwrócić uwagę, że  w przypadku, gdy dane zostały przekazane Komisji (Eurostatowi), wymagana jest zgoda krajowych urzędów statystycznych (KUS) lub innych organów krajowych, które dostarczyły te dane. Uwzględniając Rozporządzenia Nr 223/2009  w szczególności jego art. 23 wydane zostało Rozporządzenie Komisji (UE) Nr 557/2013 z dnia 17 czerwca 2013 r. w sprawie wykonania rozporządzenia (WE) nr 223/2009 Parlamentu Europejskiego i Rady w sprawie europejskiej statystyki w zakresie dostępu do poufnych danych do celów naukowych i uchylające rozporządzenie Komisji (WE) nr 831/2002^[Dz.Urz. UE L 2013 Nr 164, str. 16, European Communities (Wspólnoty Europejskie), http://eur-lex.europa.eu/]. Dokument ten określa warunki przyznawania dostępu do poufnych danych przekazywanych w celach naukowych, a także zasady współpracy pomiędzy Unią a władzami krajowymi w tym zakresie.

Ponadto, Rozporządzenie Nr 223/2009 w art. 25 statuuje, że *dane pozyskane ze źródeł, które zgodnie z prawem są ogólnodostępne i które pozostają ogólnodostępne zgodnie z przepisami krajowymi, nie są uznawane za poufne dla celów rozpowszechniania danych statystycznych uzyskanych na podstawie tych danych*.

**Rozporządzenie Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (ogólne rozporządzenie o ochronie danych)**^[Dz. Urz. UE L 119 z 04.05.2016, str. 1, z późn. zm.], zwane dalej Rozporządzeniem RODO lub RODO.

Rozporządzenie RODO nie wprowadza pełnej harmonizacji w zakresie regulacji zasad ochrony danych osobowych rozumianej jako zupełne ukształtowanie regulacji przedmiotowej bez dopuszczalności lub konieczności stosowania regulacji krajowych. Na gruncie RODO mamy do czynienia z harmonizacją częściową, w przypadku której państwa członkowskie są uprawnione do swobodnej, jednostronnej regulacji w zakresie nieunormowanym przepisami RODO, przy jednoczesnym zakazie stosowania rozwiązań sprzecznych z RODO.

Przepisy RODO mają w większości charakter prawnomaterialny, których przyjęcie jest wymagane przez państwa członkowskie, dotyczą kwestii nieuregulowanych w RODO, a więc przepisów dotyczących organów nadzorczych oraz kwestii proceduralnych.   

Analizując przepisy prawa krajowego przyjęte na podstawie Rozporządzenia RODO, w pierwszej kolejności należy wskazać na regulacje obligatoryjne. Oznacza to, że każde z państw członkowskich, w tym Rzeczpospolita Polska, zostało zobowiązane do przyjęcia krajowych przepisów regulujących ustrój organów nadzorczych oraz zasady postępowania w sprawach uregulowanych przepisami RODO, które to przepisy umożliwiają stosowanie RODO w systemie prawnym danego państwa członkowskiego. Przyjmowane przepisy krajowe muszą przestrzegać zasad niezależności i pozostawać w zgodzie z regulacjami Rozporządzenia RODO. 

Drugą grupę przepisów krajowych, których przyjęcie zostało przewidziane w RODO, stanowią przepisy, których przyjęcie przez państwa członkowskie jest fakultatywne. W tym zakresie wyróżnia się trzy kategorie tego rodzaju przepisów:

*	odesłania, w których RODO wprost przewiduje możliwość regulowania przez państwo członkowskie określonych kwestii w stosunku do tych zawartych w RODO (upoważnienia przewidujące możliwość wydania szczególnych przepisów krajowych);
*	odesłania, w których od regulacji prawa krajowego RODO uzależnia obowiązywanie przepisu RODO lub zawężenie stosowania przepisu RODO;
*	odesłania określające dopuszczalny zakres regulacji krajowej co do podstaw przetwarzania danych osobowych, które doprecyzowują RODO. 

Przypadków, w których państwa członkowskie mogą przyjąć przepisy krajowe dotyczące ochrony danych osobowych, należy poszukiwać w szczególności w Rozdziale IX Rozporządzenia RODO. Są to sytuacje dotyczące:

*	przetwarzania danych osobowych w kontekście wolności wypowiedzi i informacji;
*	przetwarzania danych zawartych w dokumentach urzędowych udostępnianych publicznie; 
*	przetwarzania krajowego numeru identyfikacyjnego;
*	przetwarzania danych osobowych w kontekście zatrudnienia;
*	przetwarzania danych osobowych do celów archiwalnych w interesie publicznym, do celów badań naukowych lub historycznych lub do celów statystycznych;
*	przetwarzania danych osobowych objętych tajemnicą zawodową^[Zob. art. 89 Rozporządzenia RODO.];
*	przetwarzania danych osobowych przez kościoły i związki wyznaniowe.

Poza przypadkami, w których przyjęcie krajowych przepisów o ochronie danych osobowych wynika z konieczności zapewnienia stosowania RODO, w ustawie z 10 maja 2018 r. o ochronie danych osobowych można znaleźć wiele przepisów, co do których decyzja o ich przyjęciu nie jest związana bezpośrednio z rozpoczęciem stosowania przepisów RODO. 

Rozpoczęcie stosowania RODO wymusiło także zmiany wielu aktów prawnych dotyczących przetwarzania danych osobowych. Wynikają one czy to z prostej zmiany nazw poszczególnych instytucji prawa ochrony danych osobowych, ze zmian ustrojowych i proceduralnych, czy też z konieczności uwzględnienia konkretnych regulacji RODO, które – jako przepisy prawa wspólnotowego – mają pierwszeństwo przed przepisami prawa krajowego.   

**Europejski Kodeks Praktyk Statystycznych**

Istotne znaczenie dla podstaw prawnych zachowania poufności w statystyce publicznej ma tzw. miękkie prawo (ang. *soft law*) . Miękkie prawo są to pokrewne prawu instrumenty, które nie posiadają żadnej mocy prawnie wiążącej albo moc wiążąca jest w jakiś sposób „słabsza" w porównaniu do mocy wiążącej tradycyjnego prawa określanego jako „twarde prawo" (ang. *hard law*).

Termin "miękkie prawo" jest także często używany w odniesieniu do różnych rodzajów quasi-prawnych instrumentów Unii Europejskiej  takich jak „kodeksy postępowania" (ang. *codes of conduct*), „kodeksy praktyk" (ang. *codes of practice*),  „wytycznych" (ang. *guidelines*), „komunikatów” (ang. *communications*) itp.

W domenie prawa Unii Europejskiej, instrumenty „miękkiego prawa” są często używane w celu zasygnalizowania, w jaki sposób Komisja Europejska będzie używała swoich kompetencji, w jaki sposób Komisja będzie wykonywała swoje zadania w ramach przysługującego jej prawa. Kluczowym instrumentem „soft law” w zakresie statystyki publicznej jest Europejski Kodeks Praktyk Statystycznych, przyjęty przez Komitet do spraw Europejskiego Systemu Statystycznego w dniu 28 sierpnia 2011 r.^[Europejski Kodeks Praktyk Statystycznych dla krajowych i wspólnotowych organów statystycznych. Przyjęty przez Komitet ds. Europejskiego Systemu Statystycznego 28 sierpnia 2011 r., znowelizowany w 2017 r. <https://ec.europa.eu/eurostat/documents/4031688/9394304/KS-02-18-142-PL-N.pdf/7ad9346a-5019-44ee-bb16-c7b7dfdb8779?t=1542711876000>] - dalej zwany Kodeksem. Jego moc została wzmocniona przez przepisy rozporządzenia 223/2009, a wdrożenie zasad objętych Kodeksem w krajach unijnych podlega cyklicznemu monitoringowi (*peer reviews*).

Do Kodeksu na gruncie prawa krajowego odwołuje się art. 25a Ustawy, który statuuje zasady realizacji zadań Prezesa Głównego Urzędu Statystycznego. Wykonując zadania określone w Ustawie, Prezes GUS kieruje się zasadami zgodnymi z Kodeksem wskazanym w art. 11 Rozporządzenia Nr 223/2009.

Kodeks opiera się na dwóch zasadniczych filarach wywodzących się z rozporządzenia 223/2009: ochronie  poufności danych (tj. nieujawnianie danych indywidualnych, zminimalizowanie ryzyka ich odtworzenia z mikrodanych zanonimizowanych lub zbiorczych) i wykorzystywania danych jednostkowych wyłącznie do celów statystycznych lub naukowych, które również stanowią podwaliny Ustawy.

Kodeks składa się z 15 zasad. W warstwie zasadniczej o poufności statystyk i ochronie danych traktuje Zasada 5. W tym obszarze zasada ta głosi, że należy bezwzględnie zagwarantować prywatność dostawcom danych, poufność informacji przez nich przekazywanych, wykorzystanie tych informacji  wyłącznie do celów statystycznych, a także bezpieczeństwo danych. W tym celu przepisy prawa powinny gwarantować poufność i bezpieczeństwo danych zarówno w zakresie przepisów prawnych a także , jak i warunków technicznych i fizycznych ochrony.  Stąd też analogicznie do art. 12 ust. 1 Ustawy, pracownicy statystyki podejmując zatrudnienie podpisują zobowiązanie do zachowania poufności statystyk  i ponoszą odpowiedzialność karną za naruszenia poufności. Kodeks wskazuje również na konieczność zapewnienia pracownikom w zakresie poufności i ochrony danych dostępności do prawnych instrukcji i wytycznych dotyczących w procesie ich przetwarzania i udostępniania statystyk i danych. Jednocześnie przyjęto, że informacje o polityce zapewnienia poufności winny być podawane do wiadomości publicznej. Kodeks zakłada także, że obowiązują przepisy regulujące kwestie fizycznego i technicznego bezpieczeństwa i integralności statystycznych baz danych oraz protokoły, które regulują dostęp do danych statystycznych dla użytkowników zewnętrznych wykorzystujących je do celów naukowych.

Do tych postulatów nawiązują również postanowienia zawarte w zasadzie 14 Kodeksu. W zasadzie 14 (spójność i porównywalność) zalecono, że zastosowanie odpowiednich mechanizmów udostępniania danych pochodzących z różnych źródeł w przypadku ich łączenia i zbiorczego wykorzystania.

Z kolei zasada 15 (dostępność i przejrzystość) stanowi między innymi, że można zezwolić na dostęp do danych dla celów badawczych (dostęp ten winien jednak być uregulowany ścisłymi zasadami lub protokołami – punkt 15.4).

:::
